Add surrounding whitespace work title cleanup bot
internetarchive/openlibrary-bots pull request #108
Opened 2021-06-08 11:09 UTC by jimman2003

## Description:
In this Pull Request we have made the following changes:
* Added a remix of making_a_bot.py but for works

2021-06-08 19:52 UTC, cclauss requested changes

2021-06-08 19:52 UTC, cclauss commented on whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py
>                  # the database may have changed since the dump was created, so call the OpenLibrary API and check again
88 characters per line max please

2021-06-08 19:52 UTC, cclauss commented on whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py
> +if "__name__" == "__main__":
```suggestion
if __name__ == "__main__”:
```
Dunder name is a builtin variable in Python.

2021-06-08 19:55 UTC, jimman2003 commented on whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py
>                  # the database may have changed since the dump was created, so call the OpenLibrary API and check again
" is one character

2021-06-10 05:09 UTC, cclauss requested changes

2021-06-10 05:09 UTC, cclauss commented on whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py
> +                )  # don't forget to log modifications!
```suggestion
                self.logger.info("|".join((olid, old_title, work.title)))  # log the modifications
```

2021-06-10 05:09 UTC, cclauss commented on whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py
> +        raise e
```suggestion
    except Exception:
        job.logger.exception("TrimTitleJob failed")
        raise
```
Or  `job.logger.exception("whitespace_work_title_cleanup failed")`

2021-06-10 05:11 UTC, cclauss commented on whitespace_work_title_cleanup_bot/whitespace_work_title_cleanup.py
> +import copy
```suggestion
#!/usr/bin/env python3

import copy
```

2021-06-10 11:55 UTC, cclauss approved these changes
Thanks much.

2022-12-04 12:16 UTC, merged